services:
  nitelite_pipeline:
    image: nitelite_pipeline
    volumes:
      - ../..:/workspaces:cached
      - /Users/Shared/data/nitelite/220513-FH135:/data/220513-FH135:cached
      - "/Users/zhafensaavedra/Google Drive/Shared drives/NITELite/NITELite_Mapmaker/data/night_horizons_test_data:/data/test_data:cached"
    command: sleep infinity
    environment: 
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
    # Not working currently
    # ports:
    #   - 5432:5432