services:
  nitelite_pipeline:
    image: nitelite_pipeline
    # TODO: Delete this. It's used for debugging
    volumes:
      - "/Users/zhafensaavedra/Google Drive/Shared drives/NITELite/NITELite_Mapmaker/data/night_horizons_test_data:/data/test_data:cached"
    environment: 
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
    ports:
      - 5432:5432