version: 0.2

# TODO: Currently running as root, if we change to non-root then change this
# run-as: Linux-user-name

env:
  shell: bash
  # TODO: Consider setting up the data directory with environment variables
  # variables:
  #   key: "value"
  #   key: "value"
        
phases:
  install:
    commands:
      # Install mountpoint
      - wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm
      - sudo yum -y install ./mount-s3.rpm
  pre_build:
    commands:
      # Mount the S3 buckets
      - mkdir data; mkdir data/referenced_images; mkdir data/nitelite_pipeline_output
      - mount-s3 nitelite.referenced-images data/referenced_images
      - mount-s3 nitelite-pipeline-output data/nitelite_pipeline_output
      # Pull the image from the registry. This is faster than building from
      # scratch, especially when cached
      - docker pull public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      # DEBUG
      - docker compose -f ./build/docker-compose.yaml \
          run \
          --volume /data:/data \
          nitelite-pipeline \
          /bin/bash -c \
          'ls /data'
      # Validate setup
      # - ./bin/mapmake.sh -c ./config/mosaic.yml -d /data --validate_only
  # build: 
  #   commands:
  #     # Run mapmake.py
  #     - ./bin/mapmake.sh -c ./config/mosaic.yml -d /data --validate_only