version: 0.2

# TODO: Currently running as root, if we change to non-root then change this
# run-as: Linux-user-name

env:
  shell: bash
  # TODO: Consider setting up the data directory with environment variables
  # variables:
  #   key: "value"
  #   key: "value"
        
phases:
  install:
    commands:
      # Install mountpoint
      - wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm
      - sudo yum -y install ./mount-s3.rpm
  pre_build:
    commands:
      # Mount the S3 buckets
      # Alternative: try mounting them *inside* the container.
      - mkdir /data; mkdir /data/input; mkdir /data/output; mkdir /data/input/referenced_images
      - mount-s3 $(INPUT_BUCKET) /data/input/referenced_images
      # Pull the image from the registry. This is faster than building from
      # scratch, especially when cached
      # - docker pull public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      # DEBUG
      # - docker build -t nitelite-pipeline -f ./validate/Dockerfile .
      - ./validate/comprehensive_validate.sh
      # Validate setup
      # - ./bin/mapmake.sh -c ./config/mosaic.yml -d /data --validate_only
  # build: 
  #   commands:
  #     # Run mapmake.py
  #     - ./bin/mapmake.sh -c ./config/mosaic.yml -d /data --validate_only