version: 0.2

# TODO: Currently running as root, if we change to non-root then change this
# run-as: Linux-user-name

env:
  shell: bash
  # TODO: Consider setting up the data directory with environment variables
  # variables:
  #   key: "value"
  #   key: "value"
        
phases:
  install:
    commands:
      - echo "Install phase"
      - mount-s3 --version
  pre_build:
    commands:
      # Login to docker registry. This isn't necessary for public repos, but may help with rate limiting
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2m6n0b5
      # Pull the image from the registry. This is faster than building from scratch
      - docker pull public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      - ./bin/validate.sh
  # build:
  #   commands:
  # post_build:
  #   commands:
  #     - ./bin/mapmake.sh