version: 0.2

# TODO: Currently running as root, if we change to non-root then change this
# run-as: Linux-user-name

env:
  shell: bash
  # TODO: Consider setting up the data directory with environment variables
  # variables:
  #   key: "value"
  #   key: "value"
        
phases:
  pre_build:
    commands:
      # Login to docker registry
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 611695165675.dkr.ecr.us-east-1.amazonaws.com
      # - docker pull public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      # - bin/validate.sh
      - docker compose -f ./build/docker-compose.yaml run -i nitelite-pipeline conda run -n nitelite-pipeline-conda python -c "import sys; print(sys.executable)"
  # build:
  #   commands:
  #     - ./bin/mapmake.sh