version: 0.2

# TODO: Currently running as root, if we change to non-root then change this
# run-as: Linux-user-name

env:
  shell: bash
  # TODO: Consider setting up the data directory with environment variables
  # variables:
  #   key: "value"
  #   key: "value"
        
phases:
  install:
    runtime-versions:
      docker: 24
  pre_build:
    commands:
      - echo Pulling image from Amazon ECR...
      - docker pull public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      - ./bin/validate.sh
  build:
    commands:
      - ./bin/mapmake.sh