version: 0.2

phases:
  install:
    commands:
      # Install mountpoint
      - wget https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm
      - sudo yum -y install ./mount-s3.rpm
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2m6n0b5
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --progress plain -f ./build/Dockerfile -t nitelite-pipeline:latest .
      - docker tag nitelite-pipeline:latest public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
  post_build:
    commands:
      - echo Build completed on `date`
      # Run the test suite
      - mkdir data; ./aws/run_tests.sh
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest