version: 0.2

# TODO: Use parameters?
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 611695165675.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nitelite-pipeline:latest .
      - docker tag nitelite-pipeline:latest 611695165675.dkr.ecr.us-east-1.amazonaws.com/nitelite-pipeline:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 611695165675.dkr.ecr.us-east-1.amazonaws.com/nitelite-pipeline:latest