version: 0.2

# TODO: Use parameters?
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i2m6n0b5
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --progress plain -f ./build/Dockerfile -t nitelite-pipeline .
      - docker tag nitelite-pipeline:latest public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest
      - ./bin/validate.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/i2m6n0b5/nitelite-pipeline:latest