Resources:
  NLPipelineCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: nitelite-pipeline
      Description: This project runs the NITELite pipeline.
      Artifacts:
        Location: !Ref OutputBucket
        Type: S3
        OverrideArtifactName: true
      Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ComputeType: BUILD_GENERAL1_LARGE
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: FLIGHT_ID
            Value: 220513-FH135
          - Name: CONFIG_FILEPATH
            Value: ./configs/metadata.yaml
          - Name: LOGGING_LEVEL
            Value: WARNING
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Location: https://github.com/AdlerFarHorizons/NITELite-pipeline.git
        BuildSpec: aws/buildspec.yaml
        Type: GITHUB
        GitSubmodulesConfig:
          FetchSubmodules: true
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      TimeoutInMinutes: 240
  NLPipelineImageCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: docker-nitelite-pipeline
      Description: |
        This project builds the docker image used by the pipeline.
        Only run if you know what you're doing.
      Artifacts: 
        Location: !Ref OutputBucket
        Type: S3
        OverrideArtifactName: true
      Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ComputeType: BUILD_GENERAL1_MEDIUM
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source: 
        Location: https://github.com/AdlerFarHorizons/NITELite-pipeline.git
        BuildSpec: aws/image-buildspec.yaml
        Type: GITHUB
        GitSubmodulesConfig:
          FetchSubmodules: true
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: NITELitePipelineServiceRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodeBuildRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ParameterStorePolicy
                Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: "*"
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: CodeCommitPolicy
                Effect: Allow
                Action:
                  - codecommit:GitPull
                Resource: "*"
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: "*"
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:AbortMultipartUpload
                  - s3:DeleteObject
                Resource: "*"
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource: "*"
              - Sid: CodeBuildDockerPolicy
                Effect: Allow
                Action:
                  - sts:GetServiceBearerToken
                  - ecr-public:GetAuthorizationToken
                  - ecr-public:BatchCheckLayerAvailability
                  - ecr-public:GetDownloadUrlForLayer
                  - ecr-public:GetRepositoryPolicy
                  - ecr-public:DescribeRepositories
                  - ecr-public:ListImages
                  - ecr-public:DescribeImages
                  - ecr-public:BatchGetImage
                  - ecr-public:ListTagsForResource
                  - ecr-public:DescribeImageScanFindings
                  - ecr-public:InitiateLayerUpload
                  - ecr-public:UploadLayerPart
                  - ecr-public:CompleteLayerUpload
                  - ecr-public:PutImage
                Resource: "*"
  NITELiteUserPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for users.
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PipelineUserCodebuildPolicy
            Effect: Allow
            Action:
              - codebuild:StartBuild
              - codebuild:StopBuild
              - codebuild:ListProjects
              - codebuild:UpdateProject
              - codebuild:CreateProject
              - codebuild:BatchGetProjects
              - codebuild:DeleteProject
            Resource: "*"
          - Sid: PipelineUserReadBucketPolicy
            Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::nitelite.metadata
              - arn:aws:s3:::nitelite.images
              - arn:aws:s3:::nitelite.referenced-images
              - arn:aws:s3:::nitelite.test-data
              - arn:aws:s3:::nitelite.pipeline-output
          - Sid: PipelineUserDeleteBucketPolicy
            Effect: Allow
            Action:
              - s3:DeleteObject
            Resource:
              - arn:aws:s3:::nitelite.pipeline-output
  OutputBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      BucketName: nitelite.pipeline-output