Resources:
  NLPipelineCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts: 
        Location: !Ref OutputBucket
        Type: S3
      Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ComputeType: BUILD_GENERAL1_MEDIUM
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source: 
        Location: https://github.com/AdlerFarHorizons/NITELite-pipeline.git
        BuildSpec: aws/buildspec.yml
        Type: GITHUB
        GitSubmodulesConfig:
          FetchSubmodules: true
  # We need to build the image on linux to use it on linux,
  # so we use aws to build the image.
  # We make a separate project for building the image, because it's faster
  # to pull the image from amazon ecr than to build it from scratch.
  NLPipelineImageCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts: 
        Location: !Ref OutputBucket
        Type: S3
      Environment: 
        Type: LINUX_CONTAINER
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ComputeType: BUILD_GENERAL1_MEDIUM
        PrivilegedMode: true
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source: 
        Location: https://github.com/AdlerFarHorizons/NITELite-pipeline.git
        BuildSpec: aws/image-buildspec.yml
        Type: GITHUB
        GitSubmodulesConfig:
          FetchSubmodules: true
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodeBuildRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ParameterStore
                Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: "*"
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: CodeCommitPolicy
                Effect: Allow
                Action:
                  - codecommit:GitPull
                Resource: "*"
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                Resource: "*"
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource: "*"
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource: "*"
              - Sid: ECRPolicy
                Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr-public:GetAuthorizationToken
                  - sts:GetServiceBearerToken
                Resource: "*"
  OutputBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: RetainExceptOnCreate
    Properties:
      BucketName: nitelite-pipeline-output