# TODO: Rename all .yaml to .yml.
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: ./build/Dockerfile
      # dockerfile: ./.devcontainer/devtest.Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /Users/Shared/data:/data:cached
      # TODO: The test data is stored on google drive, so we need to ensure
    command: sleep infinity
    # TODO: Probably define these in the stack?
    environment:
      DATABASE_URL: 'postgresql://nitelite:nitelite@database:5432/nitelite'
      FLIGHT_ID: 'FH135'
    depends_on:
      - database
  database:
    # image: postgis/postgis
    build:
      context: ..
      dockerfile: ./build/postgis.Dockerfile
    restart: always
    environment:
      POSTGRES_DB: nitelite
      POSTGRES_USER: nitelite
      POSTGRES_PASSWORD: nitelite
    volumes:
      - /Users/Shared/data/nitelite/db:/var/lib/postgresql/data
    ports:
      - 5432:5432