# TODO: Rename all .yaml to .yml.
services:
  devcontainer:
    build: 
      context: ..
      dockerfile: ./build/Dockerfile
      # dockerfile: ./.devcontainer/devtest.Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /Users/Shared/data:/data:cached
      # TODO: The test data is stored on google drive, so we need to ensure
      # that the user has access to the data.
      # - "/Users/zhafensaavedra/Google Drive/Shared drives/NITELite/NITELite_Mapmaker/data/night_horizons_test_data:/data/night_horizons_test_data:cached"
    command: sleep infinity
    # environment: 
    #   POSTGRES_DB: gis
    #   POSTGRES_USER: gis
    #   POSTGRES_PASSWORD: gis
    # ports:
    #   - 5432:5432