services:
  devcontainer:
    build: 
      context: ..
      dockerfile: ./build/Dockerfile
      # dockerfile: ./.devcontainer/devtest.Dockerfile
    volumes:
      # - ../..:/workspaces:cached
      - /Users/Shared/repos/NITELite-pipeline:/NITELite-pipeline:cached
      - /Users/Shared/data/night_horizons_test_data:/data:cached
    command: sleep infinity