services:
  nitelite:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment: 
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
    ports:
      - 5432:5432
    volumes:
      - /Users/Shared/data/nitelite/220513-FH135:/flight-data
      - ./bin:/usr/local/bin/nitelite