###############################################################################
# Example Configuration File
###############################################################################

# Indicate what type of map we want to create
mapmaker:
  map_type: mosaic

# I/O settings
io_manager:
  input_dir: /data/220513-FH135
  input_description:
    raw_images:
      directory: images/raw
      extension: ['raw', 'tif', 'tiff']
    referenced_images:
      directory: images/referenced
      extension: ['tif', 'tiff']
      pattern: 'Geo\s\d+_\d.tif'
  output_dir: /data/220513-FH135/mosaics/referenced
  file_exists: new

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state: 
  seed: 159234
