###############################################################################
# Example Configuration File
###############################################################################

# Indicate what type of map we want to create
mapmaker:
  map_type: sequential

# I/O settings
# These settings assume that the user has mounted their data directory at /data
io_manager:
  # Directory containing input files. Filepaths in input_description
  # are relative to this directory.
  input_dir: /data/nitelite/220513-FH135
  # Specifies the input data
  input_description:
    # Metadata files. We provide the exact full path relative to input_dir.
    img_log: metadata/image.log
    imu_log: metadata/PresIMULog.csv
    gps_log: metadata/GPSLog.csv
    # Images with georeferencing. We perform a search for matching files.
    referenced_images:
      # This filepath is relative to input_dir, e.g. the full path could be
      # /data/nitelite/220513-FH135/images/referenced
      directory: images/referenced
      # Only files with these extensions will be considered.
      extension: ['tif', 'tiff']
      # This is a RegEx pattern. The "1" selects nadir images only.
      pattern: 'Geo\s\d+_1.tif'
  # Where the output files will be saved
  output_dir: /data/nitelite/220513-FH135/mosaics/referenced
  # If the output directory already exists then a new directory is created
  # with a new ID attached.
  file_exists: new

# Settings for testing and training data
data_splitter:
  drop_raw_images: True

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state: 
  seed: 159234
