###############################################################################
# Example Configuration File
###############################################################################

# Indicate what type of map we want to create
mapmaker:
  map_type: sequential

# I/O settings
io_manager:
  input_dir: /data/nitelite/220513-FH135
  input_description:
    referenced_images:
      directory: images/referenced
      extension: ['tif', 'tiff']
      # The "1" in this pattern selects nadir images only.
      pattern: 'Geo\s\d+_1.tif'
    img_log: metadata/image.log
    imu_log: metadata/PresIMULog.csv
    gps_log: metadata/GPSLog.csv
  output_dir: /data/nitelite/220513-FH135/mosaics/sequential_test
  file_exists: new

# Settings for testing and training data
data_splitter:
  drop_raw_images: True

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state: 
  seed: 159234
