###############################################################################
# Example Mosaicker Config
###############################################################################

# TODO: Make an ultra simple config that includes *just* the flight ID
#       Don't try to ask users to access the ENV vars in the "override build settings"

# Indicate what stage of the pipeline to run
pipeline:
  stage: mosaicker

# I/O settings
# These settings assume that the user has mounted their data directory at /data
io_manager:
  # Specifies the input data
  input_dir: /data/input
  input_description:
    # Images with georeferencing. We perform a search for matching files.
    referenced_images:
      # This filepath is relative to input_dir
      directory: referenced_images/220513-FH135
      # This is a RegEx pattern. The "1" selects nadir images only.
      pattern: 'Geo\s\d+_1\.(tif|tiff)$'
  # Where the output files will be saved
  output_dir: /data/output/mosaic
  output_description:
    used_config: used-config.yaml
  file_exists: new

# What metadata processor to use (based on metadata format)
metadata_processor:
  version: fh135_metadata_processor

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state:
  seed: 15923
