###############################################################################
# Example Mosaicker Config
###############################################################################

# Indicate what stage of the pipeline to run
pipeline:
  stage: mosaicker

# I/O settings
# These settings assume that the user has mounted their data directory at /data
io_manager:
  # Specifies the input data
  input_dir: /data/input
  input_description:
    # Images with georeferencing. We perform a search for matching files.
    referenced_images:
      # This filepath is relative to input_dir
      directory: referenced_images/220513-FH135
      # This is a RegEx pattern. The "1" selects nadir images only.
      pattern: 'Geo\s\d+_1\.(tif|tiff)$'
  # Where the output files will be saved
  output_dir: /data/output

# Coordinate reference-system employed
crs:
  projparams: 'EPSG:3857'

random_state:
  seed: 15923
